server:
    port: 8080
    error:
        include-message: always

spring:
    data:
        mongodb:
            uri: mongodb+srv://hyankelwin:k9KNpzPOTJewEqe9@cluster0.vqyrm.mongodb.net/faculdade

integration:
    tipoVeiculo.url: http://localhost:8090