spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/locacao

server:
    port: 8085
    error:
        include-message: always

integration:
    veiculo.url: http://localhost:8080
    funcionario.url: http://localhost:8081
    cliente.url: http://localhost:8082